/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-04-21 12:52:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productOne_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-jstl-1.2.jar", Long.valueOf(1650000930325L));
    _jspx_dependants.put("jar:file:/C:/Users/aaa77/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShoppingMall/WEB-INF/lib/jstl-jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write(" .product_left{\r\n");
      out.write(" float:left;  max-width:50%; max-height: auto;display: block;\r\n");
      out.write("}\r\n");
      out.write(".product_right{\r\n");
      out.write(" float:right; max-width: 50%; display: block;\r\n");
      out.write("} */\r\n");
      out.write("/* .main_product_img{\r\n");
      out.write("  max-width:500px;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>상품 상세 페이지</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/basket.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel = \"stylesheet\" type = \"text/css\" href = \"resources/css/project.css\">\r\n");
      out.write("<link rel = \"stylesheet\" type = \"text/css\" href = \"resources/css/basket.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\" integrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function () {\r\n");
      out.write("	$('#add').click(function(){\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: 'productAdd',\r\n");
      out.write("		data : {\r\n");
      out.write("			product_idx: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', //string \r\n");
      out.write("			product_title:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', //string\r\n");
      out.write("			product_idx : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("			product_price: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" //int\r\n");
      out.write("			\r\n");
      out.write("		},\r\n");
      out.write("		success: function(result){\r\n");
      out.write("			alert(result)\r\n");
      out.write("			if(confirm(\"장바구니를 확인하시겠습니까?\")){\r\n");
      out.write("				location.href =\"basket.jsp\"\r\n");
      out.write("			}\r\n");
      out.write("		},\r\n");
      out.write("		error: function(){\r\n");
      out.write("			alert(\"ajax 에러 발생.\")\r\n");
      out.write("			}//error\r\n");
      out.write("		});//ajax\r\n");
      out.write("	});//click\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" $('#deleteBtn').click(function() {\r\n");
      out.write("	if(confirm(\"정말로 삭제하시겠습니까?\")){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: \"productDel\",\r\n");
      out.write("			data: {\r\n");
      out.write("				product_idx: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("	\r\n");
      out.write("			},\r\n");
      out.write("			success : function(result) {\r\n");
      out.write("				if(result == '1'){\r\n");
      out.write("					location.href = \"productList.jsp\"\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("			error:function(){\r\n");
      out.write("				alert('삭제 실패')\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	}); \r\n");
      out.write("	\r\n");
      out.write("		/* $('#love').click(function() {\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"createMemberLike\",\r\n");
      out.write("			data:{\r\n");
      out.write("				user_id: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("				product_idx : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("			},\r\n");
      out.write("			success: \r\n");
      out.write("\r\n");
      out.write("			 }\r\n");
      out.write("		   }\r\n");
      out.write("		\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("		\r\n");
      out.write("	*/\r\n");
      out.write("	\r\n");
      out.write("	    let likecheck = []; \r\n");
      out.write("		let user_id = []; \r\n");
      out.write("		let product_idx = []; \r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"selectMemberLikeOne\",\r\n");
      out.write("			type:'get', \r\n");
      out.write("			data:{\r\n");
      out.write("				user_id: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("				product_idx : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("			},\r\n");
      out.write("			success: function(jsonData) { \r\n");
      out.write("				\r\n");
      out.write("				console.log(jsonData)\r\n");
      out.write("				\r\n");
      out.write("				$(jsonData).each(function(index, item){\r\n");
      out.write("					\r\n");
      out.write("					likecheck.push(item.likecheck);\r\n");
      out.write("					\r\n");
      out.write("					console.log('LikeOne likecheck:'+likecheck);\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				if(likecheck == 1){\r\n");
      out.write("					console.log('이전에 좋아요 클릭한 상태')\r\n");
      out.write("					$('#likecheck').val(1); \r\n");
      out.write("					$('#likebtn').attr('class', 'btn btn-danger'); \r\n");
      out.write("				}else{\r\n");
      out.write("					console.log('이전에 좋아요를 누르지 않았음.')\r\n");
      out.write("\r\n");
      out.write("					$('#likecheck').val(''); \r\n");
      out.write("\r\n");
      out.write("					$('#likebtn').attr('class', 'btn btn-light'); \r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			 }, error:function(jsonData){\r\n");
      out.write("				 console.log('에러')\r\n");
      out.write("			 }\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		   });//ajax\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("		   $(function(){\r\n");
      out.write("				//alert('test..')\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"likeCheck\", \r\n");
      out.write("					data:{\r\n");
      out.write("						user_id: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("						product_idx : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("					},\r\n");
      out.write("					success: function(result){\r\n");
      out.write("						console.log('likecheck 값'+result)\r\n");
      out.write("						console.log('likecheck 성공')\r\n");
      out.write("						\r\n");
      out.write("						if(result==1){\r\n");
      out.write("							console.log('이전에 좋아요 클릭한 상태')\r\n");
      out.write("							$('#likeck').val(1); \r\n");
      out.write("							$('#likebtn').attr('class', 'btn btn-danger'); \r\n");
      out.write("						}else{\r\n");
      out.write("							console.log('이전에 좋아요를 누르지 않았음.')\r\n");
      out.write("							$('#likeck').val(''); \r\n");
      out.write("							$('#likebtn').attr('class', 'btn btn-light'); \r\n");
      out.write("						}\r\n");
      out.write("					},\r\n");
      out.write("					error: function() {\r\n");
      out.write("						console.log('likecheck 실패')\r\n");
      out.write("					\r\n");
      out.write("					}\r\n");
      out.write("				\r\n");
      out.write("				})\r\n");
      out.write("			}) \r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("			    $(function(){\r\n");
      out.write("				 $(\"#likeDelbtn\").on(\"click\",function(){ \r\n");
      out.write("					//alert('test..')\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url : \"likeCheckRevert\", \r\n");
      out.write("						type:'post', \r\n");
      out.write("						data:{\r\n");
      out.write("							user_id: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("							product_idx : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("						},\r\n");
      out.write("						success: function(result){\r\n");
      out.write("							console.log(location.reload )\r\n");
      out.write("							  if (self.name != 'reload') {\r\n");
      out.write("							         self.name = 'reload';\r\n");
      out.write("							         self.location.reload(true);\r\n");
      out.write("							     }\r\n");
      out.write("							     else self.name = ''; \r\n");
      out.write("							\r\n");
      out.write("						},\r\n");
      out.write("						error: function() {\r\n");
      out.write("							console.log(location.reload )\r\n");
      out.write("							\r\n");
      out.write("							  if (self.name != 'reload') {\r\n");
      out.write("							         self.name = 'reload';\r\n");
      out.write("							         self.location.reload(true);\r\n");
      out.write("							     }\r\n");
      out.write("							     else self.name = ''; \r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("						}\r\n");
      out.write("					\r\n");
      out.write("					})\r\n");
      out.write("				 })\r\n");
      out.write("			})    \r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			 $(function(){\r\n");
      out.write("				 $(\"#likebtn\").on(\"click\",function(){ \r\n");
      out.write("				//alert('test..')\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"likeCheckInsert\", \r\n");
      out.write("					data:{\r\n");
      out.write("						user_id: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("						product_idx : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("					},\r\n");
      out.write("					success: function(result){\r\n");
      out.write("						console.log('likeInsert 성공')\r\n");
      out.write("						   if (self.name != 'reload') {\r\n");
      out.write("					         self.name = 'reload';\r\n");
      out.write("					         self.location.reload(true);\r\n");
      out.write("					     }\r\n");
      out.write("					     else self.name = '';   \r\n");
      out.write("					},\r\n");
      out.write("					error: function() {\r\n");
      out.write("						console.log('likeInsert 실패')\r\n");
      out.write("						   if (self.name != 'reload') {\r\n");
      out.write("					         self.name = 'reload';\r\n");
      out.write("					         self.location.reload(true);\r\n");
      out.write("					     }\r\n");
      out.write("					     else self.name = '';  \r\n");
      out.write("					}\r\n");
      out.write("				\r\n");
      out.write("				})\r\n");
      out.write("				\r\n");
      out.write("			 })\r\n");
      out.write("		}) \r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		//에러를 찾기 위함. \r\n");
      out.write("		 error: (error) => {\r\n");
      out.write("             console.log(JSON.stringify(error));\r\n");
      out.write("		}\r\n");
      out.write("		 \r\n");
      out.write("		 \r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:'getProductIdxByLike',\r\n");
      out.write("			type:'get',\r\n");
      out.write("			success:function(jsonData){\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				product_idx = []; \r\n");
      out.write("				likecheck = []; \r\n");
      out.write("				\r\n");
      out.write("				$(jsonData).each(function(index,item){\r\n");
      out.write("					product_idx.push(item.product_idx); \r\n");
      out.write("					likecheck.push(item.likecheck); \r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				console.log('product_idx'+product_idx)\r\n");
      out.write("				console.log('likecheck'+likecheck)\r\n");
      out.write("				\r\n");
      out.write("				let data = {\r\n");
      out.write("						\r\n");
      out.write("						labels : product_idx,\r\n");
      out.write("						datasets : [{\r\n");
      out.write("							\r\n");
      out.write("							label : 'ProductIdx by Like number',\r\n");
      out.write("							data: likecheck,\r\n");
      out.write("							backgroundColor : [\r\n");
      out.write("								\r\n");
      out.write("								  'rgba(255, 99, 132, 0.2)',\r\n");
      out.write("							      'rgba(255, 159, 64, 0.2)',\r\n");
      out.write("							      'rgba(255, 205, 86, 0.2)',\r\n");
      out.write("							      'rgba(75, 192, 192, 0.2)',\r\n");
      out.write("							      'rgba(54, 162, 235, 0.2)',\r\n");
      out.write("							      'rgba(153, 102, 255, 0.2)',\r\n");
      out.write("							      'rgba(201, 203, 207, 0.2)'\r\n");
      out.write("								\r\n");
      out.write("							],\r\n");
      out.write("							borderColor: [\r\n");
      out.write("								\r\n");
      out.write("								 'rgb(255, 99, 132)',\r\n");
      out.write("							      'rgb(255, 159, 64)',\r\n");
      out.write("							      'rgb(255, 205, 86)',\r\n");
      out.write("							      'rgb(75, 192, 192)',\r\n");
      out.write("							      'rgb(54, 162, 235)',\r\n");
      out.write("							      'rgb(153, 102, 255)',\r\n");
      out.write("							      'rgb(201, 203, 207)'\r\n");
      out.write("							\r\n");
      out.write("							],\r\n");
      out.write("							\r\n");
      out.write("							borderWidth: 1\r\n");
      out.write("							\r\n");
      out.write("							}]	\r\n");
      out.write("						\r\n");
      out.write("					}; //let data\r\n");
      out.write("					\r\n");
      out.write("					let config = {\r\n");
      out.write("										type: 'bar', \r\n");
      out.write("										data : data, \r\n");
      out.write("										options : {\r\n");
      out.write("											scales:{\r\n");
      out.write("												y:{\r\n");
      out.write("													beginAtZero:true\r\n");
      out.write("												}\r\n");
      out.write("											}\r\n");
      out.write("										},\r\n");
      out.write("								};\r\n");
      out.write("					\r\n");
      out.write("							var myChart = new Chart(document.getElementById('myChart'), config); \r\n");
      out.write("				\r\n");
      out.write("						}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("				});\r\n");
      out.write("		\r\n");
      out.write("	}); //$\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* $(function(){\r\n");
      out.write("	\r\n");
      out.write("	var sum = $(\"#sum\").hasClass(\"sum\")\r\n");
      out.write("	console.log(sum);\r\n");
      out.write("});\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" 		//서버가 작동할 떄 \r\n");
      out.write(" 		//JAVA>JSTL>HTML>Javascript순으로 작동하기 떄문에 \r\n");
      out.write(" 		//Javascript에서는 jstl이나 태그의 값을 다루는데에 제한적일 수 밖에 없다. \r\n");
      out.write(" 		//다만 스크립트가 로드되기 전부터 존재하는 el값은 스크립트에서 조작이 가능하다 \r\n");
      out.write(" 		//ex) ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item1.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("(x)\r\n");
      out.write(" 		//ex) var list = '");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("'; \r\n");
      out.write(" 		\r\n");
      out.write("		function total(){\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		 var p_price1 =  document.getElementById(\"p_price1\").value; \r\n");
      out.write("		 var p_num1 = document.getElementById(\"p_num1\").value;\r\n");
      out.write("		 var total = p_price1 * p_num1 \r\n");
      out.write("		 console.log(total); \r\n");
      out.write("\r\n");
      out.write("		 \r\n");
      out.write("		 \r\n");
      out.write("		 //파라미터를 넘길 때 &구분자를 기준으로 인식하기 때문에 잊지않고 꼭 써주기. \r\n");
      out.write("		 \r\n");
      out.write("		 location.href=\"purchaseList?payment_total=\"+total+\"&user_id=\"+'");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("				 +\"&product_title=\"+'");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("				 +\"&product_idx=\"+'");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("'+\"&p_num1=\"+p_num1+\"&product_img=\"+'");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("'; \r\n");
      out.write("    	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div id = \"top\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../top.jsp", out, false);
      out.write("\r\n");
      out.write("	   <a href=\"productList.jsp\">리스트 목록으로 </a>\r\n");
      out.write("	</div> \r\n");
      out.write("	\r\n");
      out.write("	<!-- 상품 정보 -->\r\n");
      out.write("    <div class=\"product_left\"> \r\n");
      out.write("   	   <img src=\"resources/img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style = width:50%; >\r\n");
      out.write("     	 <div class=\"product_right\"> \r\n");
      out.write("		     <div style=\"display: none;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div> <!-- one.getId() -->\r\n");
      out.write("		     <div>이름:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div> \r\n");
      out.write("		     ");
      out.write("\r\n");
      out.write("		     <div>카테고리:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("		    ");
      out.write("\r\n");
      out.write("		     <div>상세 설명:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("	      	 <div>등록일:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_rgstdate.substring(0,10)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div> \r\n");
      out.write("	      	 <div>수정일:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_mdfydate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </div>\r\n");
      out.write("		     \r\n");
      out.write("		     <div class=\"subdiv\">\r\n");
      out.write("                        <div class=\"basketprice\">\r\n");
      out.write("                        	<input type=\"hidden\" name=\"p_price\" id=\"p_price1\" class=\"p_price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원\r\n");
      out.write("                       	</div>\r\n");
      out.write("                        <div class=\"num\">\r\n");
      out.write("                            <div class=\"updown\">\r\n");
      out.write("                                수량 입력[최대 99]: <br>\r\n");
      out.write("                             <input type=\"text\" name=\"p_num1\" id=\"p_num1\" size=\"2\" maxlength=\"4\" class=\"p_num\" value=\"1\" onkeyup=\"javascript:basket.changePNum(1);\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                       	구매 시 버튼 클릭:<button onclick=\"total()\"><div id = \"sum\" class=\"sum\">total</div></button>\r\n");
      out.write("\r\n");
      out.write("                    </div> 	 \r\n");
      out.write("		      	 \r\n");
      out.write("		      	 ");
      out.write("\r\n");
      out.write("	    		 \r\n");
      out.write("	    		 			<div>\r\n");
      out.write("								<button type = \"button\" id=\"likebtn\" class=\"btn btn-light\">❤</button>\r\n");
      out.write("	    		  					<button type = \"button\" id=\"likeDelbtn\" >like cancel</button>\r\n");
      out.write("	    		  			</div>\r\n");
      out.write("	    		 \r\n");
      out.write("	    		 \r\n");
      out.write("	\r\n");
      out.write("	    			<!-- jsp는 값 넘길때 붙일 것. -->\r\n");
      out.write("		      	 <!-- <button><a href=\"purchaseList\">바로구매</a></button>  -->\r\n");
      out.write("		      	 <button id = \"add\">장바구니</button> \r\n");
      out.write("		      	 <button><a href=\"reviewList.jsp?product_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">리뷰 보기</a></button>\r\n");
      out.write("		     <!-- 카테고리, 좋아요, 작업 이후에  구현되도록 수정할 것. -->\r\n");
      out.write("		    \r\n");
      out.write("		    </div>\r\n");
      out.write("     	 <div>\r\n");
      out.write("	      	 <a href=\"productInsert\"><button>상품 생성</button></a>\r\n");
      out.write("			 <a href=\"productUp?product_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><button>상품 내용 수정</button></a>\r\n");
      out.write("			 <button id=\"deleteBtn\">상품 삭제</button>\r\n");
      out.write("      	 </div>\r\n");
      out.write("      	 \r\n");
      out.write("      	 <!-- 차트를 생성하려면 Chart 클래스를 인스턴스화 차트를 그리고 싶은 캔버스의 노드, jQuery 인스턴스 또는 2D 컨텍스트를 전달 -->\r\n");
      out.write("      	 <canvas id=\"myChart\" width = \"400\" height = \"400\"></canvas>\r\n");
      out.write("      	 \r\n");
      out.write("      	 \r\n");
      out.write("      	 	<!-- -------------------------------------------- -->\r\n");
      out.write("	 	<!-- <img src=\"resources/img/buy.PNG\" style = width:30%;> \r\n");
      out.write("		 <img src=\"resources/img/love2.PNG\" style = width:30%;> \r\n");
      out.write("		 <img id = \"add\" src=\"resources/img/basketimg.PNG\" style = width:30%;>\r\n");
      out.write("		 -->	\r\n");
      out.write("  </div>	 \r\n");
      out.write("	  \r\n");
      out.write("	      <!-- </div> -->\r\n");
      out.write("   <!--  </div> -->\r\n");
      out.write("   	\r\n");
      out.write("<div id = \"total\">\r\n");
      out.write("<!-- 유저아이디가 admin 관리자인경우 S버튼 활성화 -->\r\n");
      out.write("	<!-- ");
      out.write("-->\r\n");
      out.write("	<!--	<a href=\"productInsert\"><button>생성</button></a>-->\r\n");
      out.write("	<!--	<a href=\"productUp?p_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><button id=\"updateBtn\" style=\"width: 50px;\">수정</button></a>-->\r\n");
      out.write("	<!--	<button id=\"deleteBtn\" style=\"width: 50px;\">삭제</button>-->\r\n");
      out.write("	<!--");
      out.write("-->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("	<!-- ========================================================================= -->\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		<a href=\"productInsert\"><button style=\"display:none;\">생성</button></a>\r\n");
      out.write("		<a href=\"productUp?p_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><button style=\"display:none;\">수정</button></a>\r\n");
      out.write("		<button id=\"deleteBtn\" style=\"display:none;\">삭제</button>\r\n");
      out.write("	\r\n");
      out.write("	<!-- ========================================================================= -->\r\n");
      out.write("	\r\n");
      out.write("	<!--");
      out.write("-->\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/productOne.jsp(337,21) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/productOne.jsp(352,66) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/views/productOne.jsp(353,25) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_title}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /WEB-INF/views/productOne.jsp(354,23) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_idx}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent(null);
      // /WEB-INF/views/productOne.jsp(354,95) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one.product_img}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }
}
